apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: install-maximo-app-suite-defaults
spec:
  pipelineRef:
    name: install-maximo-app-suite-9.1.x
  workspaces:
    - name: ws
      volumeClaimTemplate:
        metadata:
          name: mas-pvc
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
