apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-image-registry
spec:
  params:
    - name: registry-storageclass
      type: string
      default: ocs-external-storagecluster-cephfs
  steps:
    - name: update-image-registry
      image: quay.io/openshift/origin-cli:4.16
      script: |
        #!/usr/bin/env bash

        oc create -f <(echo '{
           "apiVersion": "v1",
           "kind": "PersistentVolumeClaim",
           "metadata": {
             "name": "image-registry-storage",
             "namespace": "openshift-image-registry"
           },
           "spec": {
             "storageClassName": "$(params.registry-storageclass)",
             "accessModes": [ "ReadWriteMany" ],
             "resources": {
               "requests": { "storage": "500Gi"
             }
           }
         }
        }');

        oc patch configs.imageregistry.operator.openshift.io cluster \
        -n openshift-image-registry \
        --type=merge \
        -p '{"spec":{"managementState":"Managed","storage":{"pvc":{"claim":"image-registry-storage"}}}}'

        oc -n openshift-image-registry patch configs.imageregistry.operator.openshift.io/cluster \
         --patch '{"spec":{"defaultRoute":true}}' --type=merge
